version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD
    environment:
      # GOROOT is not set by default
      GOROOT: ""
      GOPATH: "/go"
      PATH: "${GOPATH}/bin:${PATH}"
      BUILD_PATH: "${GOPATH}/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}"
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - setup_remote_docker
      - run: make test
      - run: make docker-build
      - run: makr push