version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD
        environment:
          CGO_ENABLED: 0
          GO111MODULE: "on"
    working_directory: /go/src/github.com/kuperiu/k8s-newrelic-adapter
    steps:
      - checkout
      - setup_remote_docker
      - run: hack/update-codegen.sh
      - run: make docker-build
      - run: make push