apiVersion: metrics.newrelic/v1alpha1
kind: ExternalMetric
metadata:
  name: sample-application
spec:
  name: sample-application
  resource:
    resource: "deployment"
  queries:
    - id: sample-application
      query: "SELECT latest(lior.k8s.num) FROM Metric WHERE metricName='lior.k8s.num' SINCE 5 minutes ago"
