apiVersion: metrics.newrelic/v1alpha1
kind: ExternalMetric
metadata:
  name: sqs-helloworld-length
spec:
  name: sqs-helloworld-length
  resource:
    resource: "deployment"
  queries:
    - id: sqs_helloworld_length
      query: "SELECT latest(lior.k8s.num) FROM Metric WHERE metricName='lior.k8s.num' SINCE 5 minutes ago"
